addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 1747)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 1747)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 1747)
engineSetModelLODDistance(1747, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 1748)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 1748)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 1748)
engineSetModelLODDistance(1748, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 1749)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 1749)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 1749)
engineSetModelLODDistance(1749, 500)
end)