addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 14588)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 14588)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 14588)
engineSetModelLODDistance(14588, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 13598)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 13598)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 13598)
engineSetModelLODDistance(13598, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 13650)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 13650)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 13650)
engineSetModelLODDistance(13650, 500)
end)