


adm_group = "Admin" -- назание alc группы, которая может использовать команды
backTime = 36000000 -- 10 раз в сколько милисекунд делать бэкап палаток и транспорта. Сейчас стоит 10 часа. 36000000
auto_load = true-- автоматическая загрузка данных при включении ресурса
auto_save = true-- автоматическое сохранение данных при выключении ресурса

serverData = {
	["vehicle"] = {
		{"MAX_Slots"},
		{"Tire_inVehicle"},
		{"Engine_inVehicle"},
		{"Parts_inVehicle"},
		-- states
		{"Tire_inVehicledam"},
		{"Engine_inVehicledam"},
		{"Parts_inVehicledam"},
		{"spawn"},
		{"fuel"},
		-- armor
		{"vehicle_armor"},
	},
	["items"] = {
	{"MAX_Slots"},
	{"serial"},
	{"name"},
		--Оружка
		{"M4A1"},
		{"M4A1 CCO"},
		{"M4A1 kamuflaż"},
		{"M4A1 z tłumikiem"},
		{"M4A1 kamuflaż z tłumikiem"},
		{"AK-101"},
		{"AK-101 z tłumikiem"},
		{"AK-101 kamuflaż"},
		{"AK-101 kamuflaż z tłumikiem"},
		{"AKM"},
		{"AKM z tłumikiem"},
		{"AKM kamuflaż"},
		{"AKM kamuflaż z tłumikiem"},
		{"SVD"},
		{"SVD kamuflaż"},
		{"WSS Wintoriez"},
		{"WSS Wintoriez kamuflaż"},
		{"AUG"},
		{"AUG z tłumikiem"},
		{"AK-74"},
		{"AK-74 z tłumikiem"},
		{"Mosin–Nagant"},
		{"Mosin–Nagant z kamuflażem"},
		{"SKS"},
		{"FN FAL"},
		{"FN FAL z tłumikiem"},
		{"WINCHESTER M70"},
		{"IZH-43"},
		{"MP-133"},
		{"MP5"},
		{"MP5 z tłumikiem"},
		{"CZ61 SCORPION"},
		{"UMP45"},
		{"M1911"},
		{"M1911 z tłumikiem"},
		{"GLOCK 19"},
		{"GLOCK 19 z tłumikiem"},
		{"MAGNUM"},
		{"Nóż myśliwski"},
		{"Topór"},
		{"Bejsbol"},
		{"Łopata"},
		{"Kij golfowy"},
		{"Piła spalinowa"},
		{"Granat dymny"},
		{"Granat hukowy"},	
		{"Granat M67"},
		{"Lornetka"},
		{"STANAG"},
		{"AK-MAG"},
		{"AK-DRUM"},
		{"SVD-MAG"},
		{"VSS-MAG"},
		{"MOSIN-CLIP"},
		{"SKS-CLIP"},
		{"FAL-MAG"},
		{"Gauge Buckshot"},
		{"MP5-K-MAG"},
		{"CZ61-MAG"},
		{"UMP45-MAG"},
		{"1911-MAG"},
		{"GLOCK-MAG"},
		{"MAGNUM-MAG"},

		{"51mm NATO"},
		{"М134 Minigun"},
		{"BGM-71 TOW"},
		
		{"Plan - blok z piasku"},
		{"Plan - worki z piaskiem"},
		{"Plan - opony"},
		{"Plan - przeciwpancerny jeż"},
		{"Plan - duży przeciwpancerny jeż"},

		{"Mina"},
		{"Piasek"},
		{"Drut"},
		{"Worek"},
		{"Opona"},
		{"Metal"},
		{"Drut kolczasty"},
		{"Niedźwiedzia pułapka"},
		
		{"Pieniądze"},
		{"Drewno"},
		{"Bandaż"},
		{"Manierka"},
		{"Butelka wody"},
		{"Водка"},
		{"Марихуана"},
		{"ЛСД"},

		{"Sardynki w puszce"},
		{"Puszka spaghetti"},
		{"Konserwa z tuńczyka"},
		{"Brzoskwinie w puszce"},
		{"Puszka bekonu"},
		
		{"Sardynki w puszce (✖)"},
		{"Puszka spaghetti (✖)"},
		{"Konserwa z tuńczyka (✖)"},
		{"Brzoskwinie w puszce (✖)"},
		{"Puszka bekonu (✖)"},
		{"Otwieracz"},
		
		{"Ryż"},
		{"Mleko"},
		{"Pomidor"},
		{"Ziemniak"},
		{"Papryka"},
		{"Banan"},
		{"Pomarańcz"},
		{"Kiwi"},
		{"Cukinia"},
		{"Borówki"},
		{"Żurawina"},
		{"Gruszka"},
		{"Jabłko"},
				
		{"Zapałki"},
		{"Morfina"},
		
		{"Puszka Coca-Coli"},
		{"Puszka Pepsi"},
		{"Kwas chlebowy"},
		{"Puszka Sprite"},
			
		{"Pusty kanister"},
		{"Pełny kanister"},
		{"Raca"},
		{"Zegarek"},
		{"Płyn fizjologiczny"},
		{"Termofor"},
		{"Anty Rad"},
		{"Węgiel medyczny"},
		{"Antybiotyk"},
		{"Adrenalina"},
		{"Arbidol"},
		{"Paczka krwii"},
		{"GPS"},
		{"Dozymetr"},
		{"Kompas"},
		{"Mapa"},
		{"Narzędzia"},
		{"Drut kolczasty"},
		{"Koło"},
		{"Akumulator"},
		{"Świeca"},
		{"Reflektor"},
		{"Gogle IR"},
		{"Gogle NV"},
		{"Namiot (wojskowy)"},
		{"Namiot (samochodowy)"},
		{"Namiot (podróżny)"},
		{"Grilowane mięso"},
		{"Surowe mięso"},
		{"Środki przeciwbólowe"},
		{"Lornetka"},
		{"Pusta manierka"},
		{"Plastikowa butelka"},
		{"Odpadki"},
		{"Radio"},
		--Стат
		{"Rukzak"},
		
		{"Strój - szary"},
		{"Strój - brązowy"},
		{"Strój - szary №2"},
		{"Strój górski - zielony"},
		{"Strój górski - PautRev"},
		{"Dresy - czerwone"},
		{"Dresy - czarne"},
		{"Strój wojskowy №1"},
		{"Dresy - niebieskie"},
		{"Strój - szary №2"},
		{"Dresy - zielone"},
		{"Dresy - brązowe"},
		{"Dresy - czarne"},
		{"Kombinezon medyczny - niebieski"},
		{"Strój wojskowy №2"},
		{"Strój wojskowy №3"},
		{"Strój wojskowy №4"},
		{"Strój wojskowy №5"},
		{"Strój wojskowy №6"},
		{"Костюм спортивный (Синий)"},
		{"Strój - czarny"},
		{"Strój TTsKO"},
		{"Strój górski - brązowy"},
		{"Strój górski - lato"},
		{"Kombinezon medyczny - czerwony"},
		{"Strój - orzeł"},

		
	
		--На голову
		{"Kominiarka z czaszką - czarna"},
		{"Kominiarka - beżowa"},
		{"Kominiarka - czarna"},
		{"Kominiarka - niebieska"},
		{"Kominiarka - zielona"},
		{"Kominiarka - różowa"},
		{"Kominiarka - biała"},
		{"Kominiarka z kamuflażem"},
		
		{"Maska Dallas"},
		{"Maska Hoxton"},
		{"Maska Wilka"},
		
		{"Maska"},
		
		{"Kask motocyklowy №1"},
		{"Kask motocyklowy №2"},
		{"Kask motocyklowy №3"},
		{"Kask motocyklowy №4"},
		{"Kask motocyklowy №5"},
		{"Kask motocyklowy №6"},
		{"Kask motocyklowy №7"},
		
		{"Bandana - kamuflaż (głęboka)"},
		{"Bandana - czarna"},
		{"Bandana - fioletowa"},
		{"Bandana - czerwona"},
		{"Bandana - żółta"},
		{"Bandana - zielona"},
		
		{"Kapelusz kowbojski - brązowy"},
		{"Kapelusz kowbojski - czarny"},
		{"Kapelusz kowbojski - ciemny brąz"},
		{"Kapelusz kowbojski - zielony"},
		{"Kapelusz kowbojski - szary"},
		{"Kapelusz kowbojski - biały"},
		
		{"Beret wojskowy - czerwony"},
		{"Beret - czarny"},
		{"Beret ONZ - ciemno niebieski"},
		{"Beret - zielony"},
		{"Beret sił obronnych - beżowy"},
		
		{"Panama - czarna"},
		{"Panama - niebieska"},
		{"Panama kamuflaż DPM"},
		{"Panama kamuflaż DĄB"},
		{"Panama kamuflaż FLECKTARN"},
		{"Panama - błękitna"},
		{"Panama - zielona"},
		{"Panama - pomarańczowa"},
		{"Panama - czerwona"},
		{"Panama - beżowa"},
		
		{"Kaptur z kamuflażem №1"},
		{"Kaptur z kamuflażem №2"},
		{"Kaptur z kamuflażem №3"},
		
		{"Płaszcz z kamuflażem №1"},
		{"Płaszcz z kamuflażem №2"},
		{"Płaszcz z kamuflażem №3"},
		
		{"Hełm balistyczny - zielony"},
		{"Hełm balistyczny - czarny"},
		{"Hełm balistyczny - niebieski"},
		{"Hełm balistyczny z kamuflażem №1"},
		{"Hełm balistyczny z kamuflażem №2"},
		{"Hełm balistyczny z kamuflażem №3"},

		{"Hełm militarny - zielony"},
		{"Hełm militarny - czarny"},
		{"Hełm militarny SWAT"},
		{"Hełm militarny z kamuflażem"},
		
		{"Czapka z nausznikami - czarna"},
		{"Czapka z nausznikami - niebieska"},
		{"Czapka z nausznikami - zielona"},
		
		{"Czapka z dzianiny - brązowa"},
		{"Czapka z dzianiny - czarna"},
		{"Czapka z dzianiny - niebieska"},
		{"Czapka z dzianiny - ciemno-brązowa"},
		{"Czapka z dzianiny - zielona"},
		{"Czapka z dzianiny - szara"},
		{"Czapka z dzianiny - czerwona"},
		
		{"Beret z daszkiem - ciemna kratka"},
		{"Beret z daszkiem - ciemny"},
		{"Beret z daszkiem - niebieski"},
		{"Beret z daszkiem - brązowa kratka"},
		{"Beret z daszkiem - brązowy"},
		{"Beret z daszkiem - szary"},
		{"Czapka - szara"},
		{"Beret z daszkiem - czerwony"},
		
		{"Kask - czarny"},
		{"Kask - niebieski"},
		{"Kask - jasno zielony"},
		{"Kask - zielony"},
		{"Kask - pomarańczowy"},
		{"Kask - czerwony"},
		{"Kask - biały"},
		{"Kask - żółty"},
		
		{"Kask strażacki - czarny"},
		{"Kask strażacki - czerwony"},
		{"Kask strażacki - biały"},
		{"Kask strażacki - żółty"},
		
		{"Hełm pilota - czarny"},
		{"Hełm pilota - biały"},
		{"Hełm pilota - zielony"},
			
		{"Husta operacyjna - niebieska"},
		{"Husta operacyjna - zielona"},
		{"Husta operacyjna - biała"},
		
		{"Czapka oficerska"},
		{"Furażerka"},
		{"Czapka policyjna"},
		
		{"Bejsbolówka №1"},
		{"Bejsbolówka №2"},
		{"Bejsbolówka №3"},
		{"Bejsbolówka №4"},
		{"Bejsbolówka №5"},
		{"Bejsbolówka №6"},
		{"Bejsbolówka №7"},
		{"Bejsbolówka №8"},
		
		{"Chusta z kamuflażem - DĄB"},
		{"Chusta - czarna"},
		{"Chusta - fioletowa"},
		{"Chusta - czerwona"},
		{"Chusta - żółta"},
		{"Chusta - zielona"},
		
		{"Podwijana czapka - czarna"},
		{"Podwijana czapka - brązowa"},
		{"Podwijana czapka - zielona"},
		{"Podwijana czapka - czerwona"},
		{"Podwijana czapka - niebieska"},
		
		{"Pilotka ze słuchawkami"},
		
		{"Czapka z pomponem - czarna"},
		{"Czapka z pomponem - niebieska"},
		{"Czapka z pomponem - brązowa"},
		{"Czapka z pomponem - czerwona"},
		{"Czapka z pomponem - zielona"},

		{"Okulary dizajnerskie"},
		{"Okulary pilotki"},
		
		--Броники навески
		{"Kamizelka z futerału i kieszeniami"}, -- 10
		{"Kamizelka wstrząsoodporna"},
		{"Kamizelka PRESS"},
		--12
		{"Kamizelka o dużej pojemności - czarna"},
		{"Kamizelka o dużej pojemności - oliwkowa"},
		{"Kamizelka o dużej pojemności"},
		--8
		{"Kamizelka - czarna"},
		{"Kamizelka kamuflaż DPM"},
		{"Kamizelka - oliwkowa"},
		{"Kamizelka - TANK"},
		
		{"Kamizelka PRESS - niebieska"},
		--8
		{"Kamizelka o dużej pojemności №2 - czarna"},
		{"Kamizelka o dużej pojemności №2 - kamuflaż DPM"},
		{"Kamizelka o dużej pojemności №2 - oliwkowa"},
		{"Kamizelka o dużej pojemności №2 - TANK"},
		
		{"Kamizelka zbrojna z kamuflażem - PRESS"},
		--12
		{"Kamizelka o dużej pojemności - oliwkowy kamuflaż"},
		--16
		{"Kamizelka SMERSH"},
		--8
		{"Kamizelka o dużej pojemności - brązowa"},
		
		{"Kamizelka zbrojna z kamuflażem - PRESS №2"},
		--8
		{"Kamizelka zbrojna z kamuflażem №1"},
		{"Kamizelka zbrojna z kamuflażem №2"},

		
		

		
		--Рюкзак 35 слот
		{"Zielony górski plecak"},
		{"Czerwony górski plecak"},
		{"Pomarańczowy górski plecak"},
		{"Niebieski górski plecak"},
		{"Górski plecak z kamuflażem"},
		--Рюкзак 28 слот
		{"Plecak Tortilla №1"},
		{"Plecak Tortilla №2"},
		{"Plecak Tortilla №3"},
		{"Plecak Tortilla №4"},
		--Рюкзак 30 слот
		{"Plecak polowy №1"},
		{"Plecak polowy №2"},
		{"Plecak polowy №3"},
		{"Plecak polowy №4"},
		{"Plecak polowy №5"},
		--Рюкзак 28 слот Марвин
		{"Żółty Drybag"},
		{"Zielony Drybag"},
		{"Czerwony Drybag"},
		{"Pomarańczowy Drybag"},
		{"Niebieski Drybag"},
		{"Czarny Drybag"},
		--Рюкзак 20
		{"Zielony plecak (Taloon)"},
		{"Pomarańczowy plecak (Taloon)"},
		{"Niebieski plecak (Taloon)"},
		{"Fioletowy plecak (Taloon)"},
		{"Plecak z kamuflażem (Taloon)"},
		--Рюкзак 25
		{"Plecak szturmowy z kamuflażem"},
		{"Czarny szturmowy"},
		{"Zielony szturmowy"},
		
		{"Plecak SMERSH"},
		{"Torba domowa"},
		{"Skórzana torba"},
		{"Oryginalny skórzany plecak"},
		{"Ręcznie robiony plecak"},
		{"Ręcznie robiony skórzany plecak"},
		{"Teczka dziecięca"},
		{"Plecak Coyote"},
		
		{"Pancerz sam."},
	},
}