addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 1941)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 1941)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 1941)
engineSetModelLODDistance(1941, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 2429)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 2429)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 2429)
engineSetModelLODDistance(2429, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 2465)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 2465)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 2465)
engineSetModelLODDistance(2465, 500)
end)