addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 2624)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 2624)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 2624)
engineSetModelLODDistance(2624, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 3081)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 3081)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 3081)
engineSetModelLODDistance(3081, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 13625)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 13625)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 13625)
engineSetModelLODDistance(13625, 500)
end)