addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 14838)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 14838)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 14838)
engineSetModelLODDistance(14838, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 14801)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 14801)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 14801)
engineSetModelLODDistance(14801, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 1541)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 1541)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 1541)
engineSetModelLODDistance(1541, 500)
end)