addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 1700)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 1700)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 1700)
engineSetModelLODDistance(1700, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 1701)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 1701)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 1701)
engineSetModelLODDistance(1701, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 1717)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 1717)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 1717)
engineSetModelLODDistance(1717, 500)
end)