---GIVE

addEvent("onAdminkill", true)



addEventHandler("onAdminkill", root,
function(pName)
	setElementData(getPlayerFromName(pName), "blood", -18)
	outputChatBox("Вы убили игрока: "..pName, source, 255, 255, 0)
	outputChatBox("Вас убил админ", getPlayerFromName(pName), 255, 255, 0)
end )



addEvent("onAdminSetTOPTent", true)
function medtent()
local x, y, z = getElementPosition(source)
tent = createObject(2218, x , y +4 , z -0.9)
setObjectScale(tent, 1)
tentCol = createColSphere(x , y, z,  4)
attachElements(tentCol, tent, 0, 0, 0)
setElementData(tentCol, "parent", tent)
setElementData(tent, "parent", tentCol)
setElementData(tentCol, "tent", true)
setElementData(tentCol, "vehicle", true)
setElementData(tentCol, "MAX_Slots", 252)
		setElementData(tentCol,"M4A1",2)
		setElementData(tentCol,"M4A1 CCO",2)
		setElementData(tentCol,"AK-101",2)
		setElementData(tentCol,"AKM",2)
		setElementData(tentCol,"SVD",2)
		setElementData(tentCol,"WSS Wintoriez",2)
		setElementData(tentCol,"STANAG",300)
		setElementData(tentCol,"AK-MAG",300)
		setElementData(tentCol,"AK-DRUM",300)
		setElementData(tentCol,"SVD-MAG",50)
		setElementData(tentCol,"VSS-MAG",50)
		setElementData(tentCol,"Pieniądze",500)
		setElementData(tentCol,"Płyn fizjologiczny",7)
		setElementData(tentCol,"Termofor",7)
		setElementData(tentCol,"Bandaż",8)
		setElementData(tentCol,"Paczka krwii",7)
		setElementData(tentCol,"Morfina",7)
		setElementData(tentCol,"Paczka krwii",7)
		setElementData(tentCol,"Аптечка",7)
		setElementData(tentCol,"Paczka krwii",7)
		setElementData(tentCol,"Środki przeciwbólowe",7)
		setElementData(tentCol,"Pieniądze",500)
		setElementData(tentCol,"Kominiarka z czaszką - czarna",1)
		setElementData(tentCol,"Kominiarka - beżowa",1)
		setElementData(tentCol,"Kominiarka - czarna",1)
		setElementData(tentCol,"Kominiarka - niebieska",1)
		setElementData(tentCol,"Kominiarka - zielona",1)
		setElementData(tentCol,"Kominiarka - różowa",1)
		setElementData(tentCol,"Kominiarka - biała",1)
		setElementData(tentCol,"Kominiarka z kamuflażem",1)
		setElementData(tentCol,"Maska Dallas",1)
		setElementData(tentCol,"Maska Hoxton",1)
		setElementData(tentCol,"Maska Wilka",1)
		setElementData(tentCol,"Maska",1)
		setElementData(tentCol,"Bandana - kamuflaż (głęboka)",1)
		setElementData(tentCol,"Bandana - czarna",1)
		setElementData(tentCol,"Bandana - fioletowa",1)
		setElementData(tentCol,"Bandana - czerwona",1)
		setElementData(tentCol,"Bandana - żółta",1)
		setElementData(tentCol,"Bandana - zielona",1)
		setElementData(tentCol,"Beret wojskowy - czerwony",1)
		setElementData(tentCol,"Beret - czarny",1)
		setElementData(tentCol,"Beret ONZ - ciemno niebieski",1)
		setElementData(tentCol,"Beret - zielony",1)
		setElementData(tentCol,"Beret sił obronnych - beżowy",1)
		setElementData(tentCol,"Kaptur z kamuflażem №1",1)
		setElementData(tentCol,"Kaptur z kamuflażem №2",1)
		setElementData(tentCol,"Kaptur z kamuflażem №3",1)
		setElementData(tentCol,"Płaszcz z kamuflażem №1",1)
		setElementData(tentCol,"Płaszcz z kamuflażem №2",1)
		setElementData(tentCol,"Płaszcz z kamuflażem №3",1)
		setElementData(tentCol,"Hełm balistyczny - zielony",1)
		setElementData(tentCol,"Hełm balistyczny - czarny",1)
		setElementData(tentCol,"Hełm balistyczny - niebieski",1)
		setElementData(tentCol,"Hełm balistyczny z kamuflażem №1",1)
		setElementData(tentCol,"Hełm balistyczny z kamuflażem №2",1)
		setElementData(tentCol,"Hełm balistyczny z kamuflażem №3",1)
		setElementData(tentCol,"Hełm militarny - zielony",1)
		setElementData(tentCol,"Hełm militarny - czarny",1)
		setElementData(tentCol,"Hełm militarny SWAT",1)
		setElementData(tentCol,"Hełm militarny z kamuflażem",1)
		setElementData(tentCol,"Strój - szary",1)
		setElementData(tentCol,"Strój - brązowy",1)
		setElementData(tentCol,"Strój - szary №2",1)
		setElementData(tentCol,"Strój górski - zielony",1)
		setElementData(tentCol,"Strój górski - PautRev",1)
		setElementData(tentCol,"Dresy - czerwone",1)
		setElementData(tentCol,"Dresy - czarne",1)
		setElementData(tentCol,"Strój wojskowy №1",1)
		setElementData(tentCol,"Dresy - niebieskie",1)
		setElementData(tentCol,"Strój - szary №2",1)
		setElementData(tentCol,"Dresy - zielone",1)
		setElementData(tentCol,"Dresy - brązowe",1)
		setElementData(tentCol,"Dresy - czarne",1)
		setElementData(tentCol,"Kombinezon medyczny - niebieski",1)
		setElementData(tentCol,"Strój wojskowy №2",1)
		setElementData(tentCol,"Strój wojskowy №3",1)
		setElementData(tentCol,"Strój wojskowy №4",1)
		setElementData(tentCol,"Strój wojskowy №5",1)
		setElementData(tentCol,"Strój wojskowy №6",1)
		setElementData(tentCol,"Костюм спортивный (Синий)",1)
		setElementData(tentCol,"Strój - czarny",1)
		setElementData(tentCol,"Strój TTsKO",1)
		setElementData(tentCol,"Strój górski - brązowy",1)
		setElementData(tentCol,"Strój górski - lato",1)
		setElementData(tentCol,"Kombinezon medyczny - czerwony",1)
		setElementData(tentCol,"Strój - orzeł",1)
		setElementData(tentCol,"Kamizelka zbrojna z kamuflażem - PRESS",1)
		setElementData(tentCol,"Kamizelka SMERSH",1)
		setElementData(tentCol,"Kamizelka o dużej pojemności - brązowa",1)
		setElementData(tentCol,"Kamizelka zbrojna z kamuflażem - PRESS №2",1)
		setElementData(tentCol,"Kamizelka zbrojna z kamuflażem №1",1)
		setElementData(tentCol,"Kamizelka zbrojna z kamuflażem №2",1)
end
addEventHandler("onAdminSetTOPTent", root, medtent)


function manipulateVehicle(typ,veh)
	if typ == "delall" then
		vehicles = getElementsByType("vehicle") 
		for i,v in ipairs(vehicles) do 
			local col = getElementData(v,"parent") 
			destroyElement(col) 
			destroyElement(v) 
		end 
	elseif typ == "del" then
		local col = getElementData(veh, "parent") 
		destroyElement(col) 
		destroyElement(veh)
	elseif typ == "delallad" then
		vehicles = getElementsByType("vehicle") 
		for i,v in ipairs(vehicles) do 
			local col = getElementData(v,"parent") 
			if getElementData(col,"adminveh") == true then
				destroyElement(col) 
				destroyElement(v) 
			end
		end 
	elseif typ == "explode" then
		setElementHealth(veh,0)
		blowVehicle(veh,false)
	elseif typ == "repair" then
		setElementHealth(veh,1000)
		fixVehicle(veh)
		local col = getElementData(veh,"parent") 
		setElementData(col,"vehicle_armor",1000)
	elseif typ == "refuel10" then
		local col = getElementData(veh,"parent")
		setElementData(col, "fuel", 10)
	elseif typ == "refuel30" then
		local col = getElementData(veh,"parent")
		setElementData(col, "fuel", 30)
	elseif typ == "refuel50" then
		local col = getElementData(veh,"parent")
		setElementData(col, "fuel", 50)
	elseif typ == "refuel60" then
		local col = getElementData(veh,"parent")
		setElementData(col, "fuel", 60)
	elseif typ == "refuel80" then
		local col = getElementData(veh,"parent")
		setElementData(col, "fuel", 80)
	elseif typ == "refuel100" then
		local col = getElementData(veh,"parent")
		setElementData(col, "fuel", 100)
	elseif typ == "refuel140" then
		local col = getElementData(veh,"parent")
		setElementData(col, "fuel", 140)
	elseif typ == "svech" then
		local col = getElementData(veh,"parent")
		setElementData(col,"Engine_inVehicle",1)
		setElementData(col,"Parts_inVehicle",1)
	elseif typ == "svech2" then
		local col = getElementData(veh,"parent")
		setElementData(col,"Tire_inVehicle",2)
	elseif typ == "svech3" then
		local col = getElementData(veh,"parent")
		setElementData(col,"Tire_inVehicle",3)
	elseif typ == "svech4" then
		local col = getElementData(veh,"parent")
		setElementData(col,"Tire_inVehicle",4)
	elseif typ == "svech6" then
		local col = getElementData(veh,"parent")
		setElementData(col,"Tire_inVehicle",6)
	elseif typ == "svech8" then
		local col = getElementData(veh,"parent")
		setElementData(col,"Tire_inVehicle",8)
	elseif typ == "on" then
		local col = getElementData(veh,"parent")
		setVehicleEngineState(veh, true)
	elseif typ == "off" then
		local col = getElementData(veh,"parent")
		setElementData(col,"Engine_inVehicle",0)
		setElementData(col,"Parts_inVehicle",0)
		setElementData(col,"Tire_inVehicle",0)
		setElementData(col, "fuel", 0)
		setElementData(col,"vehicle_armor",0)
		setVehicleEngineState(veh, false)
		
	elseif typ == "konvoi1" then
	local col = getElementData(veh,"parent")
		setElementData(col,"M4A1",2)
		setElementData(col,"AK-101",2)
		setElementData(col,"AKM",2)
		setElementData(col,"SVD",2)
		setElementData(col,"WSS Wintoriez",2)
		setElementData(col,"STANAG",300)
		setElementData(col,"AK-MAG",300)
		setElementData(col,"AK-DRUM",300)
		setElementData(col,"SVD-MAG",50)
		setElementData(col,"VSS-MAG",50)
		setElementData(col,"Pieniądze",500)
	elseif typ == "konvoi2" then
	local col = getElementData(veh,"parent")
		setElementData(col,"Płyn fizjologiczny",7)
		setElementData(col,"Termofor",7)
		setElementData(col,"Bandaż",8)
		setElementData(col,"Paczka krwii",7)
		setElementData(col,"Morfina",7)
		setElementData(col,"Paczka krwii",7)
		setElementData(col,"Аптечка",7)
		setElementData(col,"Paczka krwii",7)
		setElementData(col,"Środki przeciwbólowe",7)
		setElementData(col,"Pieniądze",500)

	elseif typ == "konvoi3" then
	local col = getElementData(veh,"parent")
		setElementData(col,"Kominiarka z czaszką - czarna",1)
		setElementData(col,"Kominiarka - beżowa",1)
		setElementData(col,"Kominiarka - czarna",1)
		setElementData(col,"Kominiarka - niebieska",1)
		setElementData(col,"Kominiarka - zielona",1)
		setElementData(col,"Kominiarka - różowa",1)
		setElementData(col,"Kominiarka - biała",1)
		setElementData(col,"Kominiarka z kamuflażem",1)
		setElementData(col,"Maska Dallas",1)
		setElementData(col,"Maska Hoxton",1)
		setElementData(col,"Maska Wilka",1)
		setElementData(col,"Maska",1)
		setElementData(col,"Bandana - kamuflaż (głęboka)",1)
		setElementData(col,"Bandana - czarna",1)
		setElementData(col,"Bandana - fioletowa",1)
		setElementData(col,"Bandana - czerwona",1)
		setElementData(col,"Bandana - żółta",1)
		setElementData(col,"Bandana - zielona",1)
		setElementData(col,"Beret wojskowy - czerwony",1)
		setElementData(col,"Beret - czarny",1)
		setElementData(col,"Beret ONZ - ciemno niebieski",1)
		setElementData(col,"Beret - zielony",1)
		setElementData(col,"Beret sił obronnych - beżowy",1)
		setElementData(col,"Kaptur z kamuflażem №1",1)
		setElementData(col,"Kaptur z kamuflażem №2",1)
		setElementData(col,"Kaptur z kamuflażem №3",1)
		setElementData(col,"Płaszcz z kamuflażem №1",1)
		setElementData(col,"Płaszcz z kamuflażem №2",1)
		setElementData(col,"Płaszcz z kamuflażem №3",1)
		setElementData(col,"Hełm balistyczny - zielony",1)
		setElementData(col,"Hełm balistyczny - czarny",1)
		setElementData(col,"Hełm balistyczny - niebieski",1)
		setElementData(col,"Hełm balistyczny z kamuflażem №1",1)
		setElementData(col,"Hełm balistyczny z kamuflażem №2",1)
		setElementData(col,"Hełm balistyczny z kamuflażem №3",1)
		setElementData(col,"Hełm militarny - zielony",1)
		setElementData(col,"Hełm militarny - czarny",1)
		setElementData(col,"Hełm militarny SWAT",1)
		setElementData(col,"Hełm militarny z kamuflażem",1)
		setElementData(col,"Strój TTsKO",1)
		setElementData(col,"Strój górski - brązowy",1)
		setElementData(col,"Strój górski - lato",1)
		setElementData(col,"Kombinezon medyczny - czerwony",1)
		setElementData(col,"Strój - orzeł",1)
		setElementData(col,"Kamizelka zbrojna z kamuflażem - PRESS",1)
		setElementData(col,"Kamizelka SMERSH",1)
		setElementData(col,"Kamizelka o dużej pojemności - brązowa",1)
		setElementData(col,"Kamizelka zbrojna z kamuflażem - PRESS №2",1)
		setElementData(col,"Kamizelka zbrojna z kamuflażem №1",1)
		setElementData(col,"Kamizelka zbrojna z kamuflażem №2",1)
		

		

		
		setElementData(col,"Pieniądze",500)
	end
	end 
addEvent("manipulateVehicle",true)
addEventHandler("manipulateVehicle",getRootElement(),manipulateVehicle)


