addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 1718)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 1718)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 1718)
engineSetModelLODDistance(1718, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 1719)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 1719)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 1719)
engineSetModelLODDistance(1719, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 1729)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 1729)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 1729)
engineSetModelLODDistance(1729, 500)
end)