SystemBind = "F9" 


--Give Seting !	
items = {
	 ["broń"] = {
       "M4A1",
       "M4A1 CCO",
		"M4A1 kamuflaż",
		"M4A1 z tłumikiem",
		"M4A1 kamuflaż z tłumikiem",
		"AK-101",
		"AK-101 z tłumikiem",
		"AK-101 kamuflaż",
		"AK-101 kamuflaż z tłumikiem",
		"AKM",
		"AKM z tłumikiem",
		"AKM kamuflaż",
		"AKM kamuflaż z tłumikiem",
		"SVD",
		"SVD kamuflaż",
		"WSS Wintoriez",
		"WSS Wintoriez kamuflaż",
		"AUG",
		"AUG z tłumikiem",
		"AK-74",
		"AK-74 z tłumikiem",
		"Mosin–Nagant",
		"Mosin–Nagant z kamuflażem",
		"SKS",
		"FN FAL",
		"FN FAL z tłumikiem",
		"WINCHESTER M70",
		"IZH-43",
		"MP-133",
		"MP5",
		"MP5 z tłumikiem",
		"CZ61 SCORPION",
		"UMP45",
		"M1911",
		"M1911 z tłumikiem",
		"GLOCK 19",
		"GLOCK 19 z tłumikiem",
		"MAGNUM",
		"Nóż myśliwski",
		"Topór",
		"Bejsbol",
		"Łopata",
		"Kij golfowy",
		"Granat dymny",
		"Granat hukowy"	,	
		"Granat M67",
		"Lornetka",
		"Piła spalinowa",
    },
    
    ["AMUNICJA"] = {
		"51mm NATO",--, 'magm4.png',256,256,"Описание1", "Подробное описание"},
		"BGM-71 TOW",--, 'magm4.png',256,256,"Описание1", "Подробное описание"},
        "STANAG",
		"AK-MAG",
		"AK-DRUM",
		"SVD-MAG",
		"VSS-MAG",
		"MOSIN-CLIP",
		"SKS-CLIP",
		"FAL-MAG",
		"Gauge Buckshot",
		"MP5-K-MAG",
		"CZ61-MAG",
		"UMP45-MAG",
		"1911-MAG",
		"GLOCK-MAG",
		"MAGNUM-MAG",
    },
    
    ["ŻYWNOŚĆ"] = {
		"Sardynki w puszce",--,'22.dds',256,256,"Описание1", "Подробное описание"},
		"Puszka spaghetti",--,'21.dds',256,256,"Описание1", "Подробное описание"},
		"Konserwa z tuńczyka",--,'23.dds',256,256,"Описание1", "Подробное описание"},
		"Brzoskwinie w puszce",--,'31.dds',256,256,"Описание1", "Подробное описание"},
		"Puszka bekonu",--,'30.dds',256,256,"Описание1", "Подробное описание"},
		
		"Sardynki w puszce (✖)",--,'22.dds',256,256,"Описание1", "Подробное описание"},
		"Puszka spaghetti (✖)",--,'21.dds',256,256,"Описание1", "Подробное описание"},
		"Konserwa z tuńczyka (✖)",--,'23.dds',256,256,"Описание1", "Подробное описание"},
		"Brzoskwinie w puszce (✖)",--,'31.dds',256,256,"Описание1", "Подробное описание"},
		"Puszka bekonu (✖)",--,'30.dds',256,256,"Описание1", "Подробное описание"},
		
		"Ryż",--,'24.dds',256,256,"Описание1", "Подробное описание"},
		"Mleko",--,'can.png',256,256,"Описание1", "Подробное описание"},
		"Pomidor",--,'25.dds',256,256,"Описание1", "Подробное описание"},
		"Ziemniak",--,'29.dds',256,256,"Описание1", "Подробное описание"},
		"Papryka",--,'can.png',256,256,"Описание1", "Подробное описание"},
		"Banan",--,'28.dds',256,256,"Описание1", "Подробное описание"},
		"Pomarańcz",--,'27.dds',256,256,"Описание1", "Подробное описание"},
		"Kiwi",--,'25.dds',256,256,"Описание1", "Подробное описание"},
		"Cukinia",--,'34.dds',256,256,"Описание1", "Подробное описание"},
		"Borówki",--,'33.dds',256,256,"Описание1", "Подробное описание"},
		"Żurawina",--,'32.dds',256,256,"Описание1", "Подробное описание"},
		"Gruszka",--,'can.png',256,256,"Описание1", "Подробное описание"},

		"Surowe mięso",--,'can.png',256,256,"Описание1", "Подробное описание"},
		
		"Puszka Coca-Coli",--,'20.dds', 256, 256,"Описание1", "Подробное описание"},
		"Puszka Pepsi",--,'36.dds', 256, 256,"Описание1", "Подробное описание"},
		"Kwas chlebowy",--,'10.dds', 256, 256,"Описание1", "Подробное описание"},
		"Puszka Sprite",--,'35.dds', 256, 256,"Описание1", "Подробное описание"},
		
		"Manierka",--,'46.dds', 256, 256,"Описание1", "Подробное описание"},
		"Butelka wody",--,'19.dds', 256, 256,"Описание1", "Подробное описание"},
		"Водка",--,'cola.png', 256, 256,"Описание1", "Подробное описание"},
		"Марихуана",--,'cola.png', 256, 256,"Описание1", "Подробное описание"},
		"ЛСД",--,'cola.png', 256, 256,"Описание1", "Подробное описание"},
		
		"Grilowane mięso",--,'cola.png', 256, 256,"Описание1", "Подробное описание"},
    },
    
   ["Рюкзаки"] = {
		--Рюкзак 35 слот
		"Zielony górski plecak",
		"Czerwony górski plecak",
		"Pomarańczowy górski plecak",
		"Niebieski górski plecak",
		"Górski plecak z kamuflażem",
		--Рюкзак 28 слот
		"Plecak Tortilla №1",
		"Plecak Tortilla №2",
		"Plecak Tortilla №3",
		"Plecak Tortilla №4",
		--Рюкзак 30 слот
		"Plecak polowy №1",
		"Plecak polowy №2",
		"Plecak polowy №3",
		"Plecak polowy №4",
		"Plecak polowy №4",
		--Рюкзак 28 слот Marvin
		"Żółty Drybag",
		"Zielony Drybag",
		"Czerwony Drybag",
		"Pomarańczowy Drybag",
		"Niebieski Drybag",
		"Czarny Drybag",
		--Рюкзак 20 слот 
		"Zielony plecak (Taloon)",
		"Pomarańczowy plecak (Taloon)",
		"Niebieski plecak (Taloon)",
		"Fioletowy plecak (Taloon)",
		"Plecak z kamuflażem (Taloon)",
		--Рюкзак 25
		"Plecak szturmowy z kamuflażem",
		"Czarny szturmowy",
		"Zielony szturmowy",
		
		"Plecak SMERSH",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
		"Torba domowa",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
		"Skórzana torba",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
		"Oryginalny skórzany plecak",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
		"Ręcznie robiony plecak",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
		"Ręcznie robiony skórzany plecak",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
		"Teczka dziecięca",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
		"Plecak Coyote",--, 'wood.png',128,128,"Описание1", "Подробное описание", "Ubierz plecak"},
	},
    
	["Пояс"] = {
	
		"Plan - blok z piasku",
		"Plan - worki z piaskiem",
		"Plan - opony",
		"Plan - przeciwpancerny jeż",
		"Plan - duży przeciwpancerny jeż",
		"Pancerz sam.",
		"Drewno",
		"Bandaż",
		"Zapałki",
		"Morfina",
		"Pusty kanister",
		"Pełny kanister",
		"Raca",
		"Zegarek",
		"Płyn fizjologiczny",
		"Termofor",
		"Paczka krwii",
		"GPS",
		"Kompas",
		"Mapa",
		"Narzędzia",
		"Drut kolczasty",
		"Koło",
		"Akumulator",
		"Świeca",
		"Reflektor",
		"Gogle IR",
		"Gogle NV",
		"Namiot (wojskowy)",
		"Namiot (podróżny)",
		"Namiot (samochodowy)",
		"Grilowane mięso",
		"Surowe mięso",
		"Środki przeciwbólowe",
		"Lornetka",
		
		"Pusta manierka",
		"Plastikowa butelka",
		"Pieniądze",
		
		"М134 Minigun",--, 'wood.png',128,128,"Описание1", "Подробное описание"},
		"Mina",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Ustaw minę"},
		"Писок",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Zbierz"},
		"Drut",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Zbierz"},
		"Worek",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Zbierz"},
		"Opona",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Zbierz"},
		"Metal",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Zbierz"},
		"Drut kolczasty",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Rozciągnij"},
		"Niedźwiedzia pułapka",--, 'clothes.png',128,128,"Описание1", "Подробное описание","Rozłóż pułapkę"},
		
		"Gogle NV",--, 'wood.png',128,128,"Описание1", "Подробное описание"},
		"Gogle IR",--, 'wood.png',128,128,"Описание1", "Подробное описание"},
		"Mapa",--, '47.dds',128,128,"Описание1", "Подробное описание"},
		"Zapałki",--, '49.dds',128,128,"Описание1", "Подробное описание","Rozpal"},
		"Zegarek",--, '51.dds',128,128,"Описание1", "Подробное описание"},
		"GPS",--, '45.dds',128,128,"Описание1", "Подробное описание"},
		"Dozymetr",--, 'wood.png',128,128,"Описание1", "Подробное описание"},
		"Narzędzia",--, '5.dds',128,128,"Описание1", "Подробное описание"},
		"Otwieracz",--, '6.dds',128,128,"Описание1", "Подробное описание"},
		"Kompas",--, 'wood.png',128,128,"Описание1", "Подробное описание"},
	},
    
	["Медикаменты"] = {
		"Bandaż",--, '4.dds',128,128,"Описание1", "Подробное описание","Zabandażuj"},
		"Płyn fizjologiczny",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Termofor",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Środki przeciwbólowe",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Morfina",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Paczka krwii",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Anty Rad",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Węgiel medyczny",--, '50.dds',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Antybiotyk",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Adrenalina",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
		"Arbidol",--, 'morphine.png',128,128,"Описание1", "Подробное описание","Zaaplikuj"},
	},
    
	["Обвеси"] = {
	--Броники навески
		"Kamizelka z futerału i kieszeniami", -- 10
		"Kamizelka wstrząsoodporna",
		"Kamizelka PRESS",
		--12
		"Kamizelka o dużej pojemności - czarna",
		"Kamizelka o dużej pojemności - oliwkowa",
		"Kamizelka o dużej pojemności",
		--8
		"Kamizelka - czarna",
		"Kamizelka kamuflaż DPM",
		"Kamizelka - oliwkowa",
		"Kamizelka - TANK",
		
		"Kamizelka PRESS - niebieska",
		--8
		"Kamizelka o dużej pojemności №2 - czarna",
		"Kamizelka o dużej pojemności №2 - kamuflaż DPM",
		"Kamizelka o dużej pojemności №2 - oliwkowa",
		"Kamizelka o dużej pojemności №2 - TANK",
		
		"Kamizelka zbrojna z kamuflażem - PRESS",
		--12
		"Kamizelka o dużej pojemności - oliwkowy kamuflaż",
		--16
		"Kamizelka SMERSH",
		--8
		"Kamizelka o dużej pojemności - brązowa",
		
		"Kamizelka zbrojna z kamuflażem - PRESS №2",
		--8
		"Kamizelka zbrojna z kamuflażem №1",
		"Kamizelka zbrojna z kamuflażem №2",
	},
    
   ["Костюм"] = {
		--Костюми..
		"Strój - szary",
		"Strój - brązowy",
		"Strój - szary №2",
		"Strój górski - zielony",
		"Strój górski - PautRev",
		"Dresy - czerwone",
		"Dresy - czarne",
		"Strój wojskowy №1",
		"Dresy - niebieskie",
		"Strój - szary №2",
		"Dresy - zielone",
		"Dresy - brązowe",
		"Dresy - czarne",
		"Kombinezon medyczny - niebieski",
		"Strój wojskowy №2",
		"Strój wojskowy №3",
		"Strój wojskowy №4",
		"Strój wojskowy №5",
		"Strój wojskowy №6",
		"Костюм спортивный (Синий)",
		"Strój - czarny",
		"Strój TTsKO",
		"Strój górski - brązowy",
		"Strój górski - lato",
		"Kombinezon medyczny - czerwony",
		"Strój - orzeł",
	},
    
    ["UBRANIA"] = {
       	--Для голови
		"Kominiarka z czaszką - czarna",
		"Kominiarka - beżowa",
		"Kominiarka - czarna",
		"Kominiarka - niebieska",
		"Kominiarka - zielona",
		"Kominiarka - różowa",
		"Kominiarka - biała",
		"Kominiarka z kamuflażem",
		
		"Maska Dallas",
		"Maska Hoxton",
		"Maska Wilka",
		
		"Maska",
		
		"Kask motocyklowy №1",
		"Kask motocyklowy №2",
		"Kask motocyklowy №3",
		"Kask motocyklowy №4",
		"Kask motocyklowy №5",
		"Kask motocyklowy №6",
		"Kask motocyklowy №7",
		
		"Kaptur z kamuflażem №1",
		"Kaptur z kamuflażem №2",
		"Kaptur z kamuflażem №3",
		
		"Płaszcz z kamuflażem №1",
		"Płaszcz z kamuflażem №2",
		"Płaszcz z kamuflażem №3",
			
		"Hełm balistyczny - zielony",
		"Hełm balistyczny - czarny",
		"Hełm balistyczny - niebieski",
		"Hełm balistyczny z kamuflażem №1",
		"Hełm balistyczny z kamuflażem №2",
		"Hełm balistyczny z kamuflażem №3",
				
		"Bandana - kamuflaż (głęboka)",
		"Bandana - czarna",
		"Bandana - fioletowa",
		"Bandana - czerwona",
		"Bandana - żółta",
		"Bandana - zielona",
		
		"Beret wojskowy - czerwony",
		"Beret - czarny",
		"Beret ONZ - ciemno niebieski",
		"Beret - zielony",
		"Beret sił obronnych - beżowy",
		
		"Panama - czarna",
		"Panama - niebieska",
		"Panama kamuflaż DPM",
		"Panama kamuflaż DĄB",
		"Panama kamuflaż FLECKTARN",
		"Panama - błękitna",
		"Panama - zielona",
		"Panama - pomarańczowa",
		"Panama - czerwona",
		"Panama - beżowa",
		
		"Hełm militarny - zielony",
		"Hełm militarny - czarny",
		"Hełm militarny SWAT",
		"Hełm militarny z kamuflażem",
		
		"Czapka z nausznikami - czarna",
		"Czapka z nausznikami - niebieska",
		"Czapka z nausznikami - zielona",
		
		"Kapelusz kowbojski - brązowy",
		"Kapelusz kowbojski - czarny",
		"Kapelusz kowbojski - ciemny brąz",
		"Kapelusz kowbojski - zielony",
		"Kapelusz kowbojski - szary",
		"Kapelusz kowbojski - biały",
		
		"Czapka z dzianiny - brązowa",
		"Czapka z dzianiny - czarna",
		"Czapka z dzianiny - niebieska",
		"Czapka z dzianiny - ciemno-brązowa",
		"Czapka z dzianiny - zielona",
		"Czapka z dzianiny - szara",
		"Czapka z dzianiny - czerwona",
		
		"Beret z daszkiem - ciemna kratka",
		"Beret z daszkiem - ciemny",
		"Beret z daszkiem - niebieski",
		"Beret z daszkiem - brązowa kratka",
		"Beret z daszkiem - brązowy",
		"Beret z daszkiem - szary",
		"Czapka - szara",
		"Beret z daszkiem - czerwony",
		
		"Kask - czarny",
		"Kask - niebieski",
		"Kask - jasno zielony",
		"Kask - zielony",
		"Kask - pomarańczowy",
		"Kask - czerwony",
		"Kask - biały",
		"Kask - żółty",
		
		"Kask strażacki - czarny",
		"Kask strażacki - czerwony",
		"Kask strażacki - biały",
		"Kask strażacki - żółty",
		
		"Hełm pilota - czarny",
		"Hełm pilota - biały",
		"Hełm pilota - zielony",
		
		"Husta operacyjna - niebieska",
		"Husta operacyjna - zielona",
		"Husta operacyjna - biała",
		
		"Czapka oficerska",
		"Furażerka",
		"Czapka policyjna",
		
		"Bejsbolówka №1",
		"Bejsbolówka №2",
		"Bejsbolówka №3",
		"Bejsbolówka №4",
		"Bejsbolówka №5",
		"Bejsbolówka №6",
		"Bejsbolówka №7",
		"Bejsbolówka №8",

		"Chusta z kamuflażem - DĄB",
		"Chusta - czarna",
		"Chusta - fioletowa",
		"Chusta - czerwona",
		"Chusta - żółta",
		"Chusta - zielona",
		
		"Podwijana czapka - czarna",
		"Podwijana czapka - brązowa",
		"Podwijana czapka - zielona",
		"Podwijana czapka - czerwona",
		"Podwijana czapka - niebieska",
	
		"Pilotka ze słuchawkami",
		
		"Czapka z pomponem - czarna",
		"Czapka z pomponem - niebieska",
		"Czapka z pomponem - brązowa",
		"Czapka z pomponem - czerwona",
		"Czapka z pomponem - zielona",
		
		"Okulary dizajnerskie",
		"Okulary pilotki",
    },
    
    ["Статс"] = {
		"Inventory",
		"Inventory_Setting",
		"bandit",
		"currentweapon_1",
		"currentweapon_2",
		"currentweapon_3",
		"clothGila",
		"clothEis",
		"clothBody",
		"clothHead",
		"clothHeadN",
		"pain",
		"cold",
		"infection",
		"brokenbone",
		"alivetime",
		"skin",
		"blood",
		"food",
		"thirst",
		"sleep",
		"radiation",
		"temperature",
		"bleeding",
		"humanity",
		"zombieskilled",
		"headshots",
		"murders",
		"banditskilled",
		"notComa",
		"inComa",
		"RadioChannel",
		"GPSChannel",
		"sick",
		"infection_zom",
		"grip",
		"alcogol",
		"marihuana",
		"lsd",
		"Boroda",
    }
}
	