addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('object1.txd',true)
engineImportTXD(txd, 1736)
local dff = engineLoadDFF('object1.dff', 0)
engineReplaceModel(dff, 1736)
local col = engineLoadCOL('object1.col')
engineReplaceCOL(col, 1736)
engineSetModelLODDistance(1736, 500)
local txd = engineLoadTXD('object2.txd',true)
engineImportTXD(txd, 1738)
local dff = engineLoadDFF('object2.dff', 0)
engineReplaceModel(dff, 1738)
local col = engineLoadCOL('object2.col')
engineReplaceCOL(col, 1738)
engineSetModelLODDistance(1738, 500)
local txd = engineLoadTXD('object3.txd',true)
engineImportTXD(txd, 1745)
local dff = engineLoadDFF('object3.dff', 0)
engineReplaceModel(dff, 1745)
local col = engineLoadCOL('object3.col')
engineReplaceCOL(col, 1745)
engineSetModelLODDistance(1745, 500)
end)